services:
  joclud_api:
    build:
      context: .
      dockerfile: DOCKERFILE
      network: host
    restart: always
    image: joclud_api
    ports:
      - "3000:3000"
      - "443:443"
    container_name: joclud_api