services:
  joclud_api:
    build:
      context: .
      dockerfile: DOCKERFILE
      network: host
    restart: always
    image: joclud_api
    expose:
      - 80
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.joclud.rule=Host(`api.joclud.leizour.fr`)"
      - "traefik.http.routers.joclud.entrypoints=websecure"
      - "traefik.http.routers.joclud.tls=true"
      - "traefik.http.routers.joclud.tls.certresolver=myresolver"
      - "traefik.http.services.joclud.loadbalancer.server.port=80"
    container_name: joclud_api

networks:
  traefik:
    external: true