version: '3.1'

services:
  joclud_api:
    build:
      context: .
      dockerfile: DOCKERFILE
    restart: always
    volumes:
      - /home/lucien/joclud_api:/app
    ports:
      - "3000:3000"
      - "443:443"